import Head from 'next/head'
import App from './_app'

const Home = ( ) => {
  return (
    <>
      <Head>
        <title>Home Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <App />
    </>
  )
}

 export default Home

// export async function getServerSideProps ( context ) {
//   const res = await fetch('https://docs.google.com/spreadsheets/d/e/2PACX-1vRAeVzfe5Xd7y_Ojzl5BxYSTDezszUfCj5PyV_lEYDPsRCX3Ze6F_YTNteG14X_Lf7FqEtHrI7m29nt/pubhtml');
//   const text = await res.text();
//   //const json =JSON.parse();//text.substring(47).slice(0, -2));
//   return {
//     props: {homes: text}
//   }
// }